from setuptools import setup

setup(
    name='housing',
    version='',
    packages=['venv.lib.python3.7.distutils', 'venv.lib.python3.7.encodings', 'venv.lib.python3.7.importlib',
              'venv.lib.python3.7.collections', 'venv.lib.python3.7.site-packages.pip',
              'venv.lib.python3.7.site-packages.pip._vendor', 'venv.lib.python3.7.site-packages.pip._vendor.idna',
              'venv.lib.python3.7.site-packages.pip._vendor.pep517',
              'venv.lib.python3.7.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.7.site-packages.pip._vendor.certifi',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.7.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.pip._vendor.colorama',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.7.site-packages.pip._vendor.progress',
              'venv.lib.python3.7.site-packages.pip._vendor.requests',
              'venv.lib.python3.7.site-packages.pip._vendor.packaging',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.7.site-packages.pip._internal', 'venv.lib.python3.7.site-packages.pip._internal.cli',
              'venv.lib.python3.7.site-packages.pip._internal.req',
              'venv.lib.python3.7.site-packages.pip._internal.vcs',
              'venv.lib.python3.7.site-packages.pip._internal.utils',
              'venv.lib.python3.7.site-packages.pip._internal.models',
              'venv.lib.python3.7.site-packages.pip._internal.commands',
              'venv.lib.python3.7.site-packages.pip._internal.operations', 'venv.lib.python3.7.site-packages.boto',
              'venv.lib.python3.7.site-packages.boto.gs', 'venv.lib.python3.7.site-packages.boto.s3',
              'venv.lib.python3.7.site-packages.boto.ec2', 'venv.lib.python3.7.site-packages.boto.ec2.elb',
              'venv.lib.python3.7.site-packages.boto.ec2.autoscale',
              'venv.lib.python3.7.site-packages.boto.ec2.cloudwatch', 'venv.lib.python3.7.site-packages.boto.ecs',
              'venv.lib.python3.7.site-packages.boto.emr', 'venv.lib.python3.7.site-packages.boto.fps',
              'venv.lib.python3.7.site-packages.boto.iam', 'venv.lib.python3.7.site-packages.boto.kms',
              'venv.lib.python3.7.site-packages.boto.mws', 'venv.lib.python3.7.site-packages.boto.rds',
              'venv.lib.python3.7.site-packages.boto.sdb', 'venv.lib.python3.7.site-packages.boto.sdb.db',
              'venv.lib.python3.7.site-packages.boto.sdb.db.manager', 'venv.lib.python3.7.site-packages.boto.ses',
              'venv.lib.python3.7.site-packages.boto.sns', 'venv.lib.python3.7.site-packages.boto.sqs',
              'venv.lib.python3.7.site-packages.boto.sts', 'venv.lib.python3.7.site-packages.boto.swf',
              'venv.lib.python3.7.site-packages.boto.vpc', 'venv.lib.python3.7.site-packages.boto.file',
              'venv.lib.python3.7.site-packages.boto.logs', 'venv.lib.python3.7.site-packages.boto.rds2',
              'venv.lib.python3.7.site-packages.boto.mturk', 'venv.lib.python3.7.site-packages.boto.pyami',
              'venv.lib.python3.7.site-packages.boto.pyami.installers',
              'venv.lib.python3.7.site-packages.boto.pyami.installers.ubuntu',
              'venv.lib.python3.7.site-packages.boto.manage', 'venv.lib.python3.7.site-packages.boto.roboto',
              'venv.lib.python3.7.site-packages.boto.cacerts', 'venv.lib.python3.7.site-packages.boto.cognito',
              'venv.lib.python3.7.site-packages.boto.cognito.sync',
              'venv.lib.python3.7.site-packages.boto.cognito.identity', 'venv.lib.python3.7.site-packages.boto.contrib',
              'venv.lib.python3.7.site-packages.boto.glacier', 'venv.lib.python3.7.site-packages.boto.kinesis',
              'venv.lib.python3.7.site-packages.boto.mashups', 'venv.lib.python3.7.site-packages.boto.route53',
              'venv.lib.python3.7.site-packages.boto.route53.domains', 'venv.lib.python3.7.site-packages.boto.support',
              'venv.lib.python3.7.site-packages.boto.cloudhsm', 'venv.lib.python3.7.site-packages.boto.dynamodb',
              'venv.lib.python3.7.site-packages.boto.opsworks', 'venv.lib.python3.7.site-packages.boto.redshift',
              'venv.lib.python3.7.site-packages.boto.services', 'venv.lib.python3.7.site-packages.boto.vendored',
              'venv.lib.python3.7.site-packages.boto.vendored.regions',
              'venv.lib.python3.7.site-packages.boto.awslambda', 'venv.lib.python3.7.site-packages.boto.beanstalk',
              'venv.lib.python3.7.site-packages.boto.dynamodb2', 'venv.lib.python3.7.site-packages.boto.cloudfront',
              'venv.lib.python3.7.site-packages.boto.cloudtrail', 'venv.lib.python3.7.site-packages.boto.codedeploy',
              'venv.lib.python3.7.site-packages.boto.cloudsearch', 'venv.lib.python3.7.site-packages.boto.elasticache',
              'venv.lib.python3.7.site-packages.boto.cloudsearch2',
              'venv.lib.python3.7.site-packages.boto.datapipeline',
              'venv.lib.python3.7.site-packages.boto.configservice',
              'venv.lib.python3.7.site-packages.boto.directconnect',
              'venv.lib.python3.7.site-packages.boto.cloudformation',
              'venv.lib.python3.7.site-packages.boto.machinelearning',
              'venv.lib.python3.7.site-packages.boto.cloudsearchdomain',
              'venv.lib.python3.7.site-packages.boto.elastictranscoder',
              'venv.lib.python3.7.site-packages.boto.ec2containerservice', 'venv.lib.python3.7.site-packages.idna',
              'venv.lib.python3.7.site-packages.mako', 'venv.lib.python3.7.site-packages.mako.ext',
              'venv.lib.python3.7.site-packages.pytz', 'venv.lib.python3.7.site-packages.yaml',
              'venv.lib.python3.7.site-packages.boto3', 'venv.lib.python3.7.site-packages.boto3.s3',
              'venv.lib.python3.7.site-packages.boto3.ec2', 'venv.lib.python3.7.site-packages.boto3.docs',
              'venv.lib.python3.7.site-packages.boto3.dynamodb', 'venv.lib.python3.7.site-packages.boto3.resources',
              'venv.lib.python3.7.site-packages.numpy', 'venv.lib.python3.7.site-packages.numpy.ma',
              'venv.lib.python3.7.site-packages.numpy.ma.tests', 'venv.lib.python3.7.site-packages.numpy.doc',
              'venv.lib.python3.7.site-packages.numpy.fft', 'venv.lib.python3.7.site-packages.numpy.fft.tests',
              'venv.lib.python3.7.site-packages.numpy.lib', 'venv.lib.python3.7.site-packages.numpy.lib.tests',
              'venv.lib.python3.7.site-packages.numpy.core', 'venv.lib.python3.7.site-packages.numpy.core.tests',
              'venv.lib.python3.7.site-packages.numpy.f2py', 'venv.lib.python3.7.site-packages.numpy.f2py.tests',
              'venv.lib.python3.7.site-packages.numpy.tests', 'venv.lib.python3.7.site-packages.numpy.compat',
              'venv.lib.python3.7.site-packages.numpy.compat.tests', 'venv.lib.python3.7.site-packages.numpy.linalg',
              'venv.lib.python3.7.site-packages.numpy.linalg.tests', 'venv.lib.python3.7.site-packages.numpy.random',
              'venv.lib.python3.7.site-packages.numpy.random.tests', 'venv.lib.python3.7.site-packages.numpy.testing',
              'venv.lib.python3.7.site-packages.numpy.testing.tests',
              'venv.lib.python3.7.site-packages.numpy.testing._private',
              'venv.lib.python3.7.site-packages.numpy.distutils',
              'venv.lib.python3.7.site-packages.numpy.distutils.tests',
              'venv.lib.python3.7.site-packages.numpy.distutils.command',
              'venv.lib.python3.7.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.7.site-packages.numpy.matrixlib',
              'venv.lib.python3.7.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.7.site-packages.numpy.polynomial',
              'venv.lib.python3.7.site-packages.numpy.polynomial.tests', 'venv.lib.python3.7.site-packages.wheel',
              'venv.lib.python3.7.site-packages.wheel.cli', 'venv.lib.python3.7.site-packages.dotenv',
              'venv.lib.python3.7.site-packages.pandas', 'venv.lib.python3.7.site-packages.pandas.io',
              'venv.lib.python3.7.site-packages.pandas.io.sas', 'venv.lib.python3.7.site-packages.pandas.io.json',
              'venv.lib.python3.7.site-packages.pandas.io.formats',
              'venv.lib.python3.7.site-packages.pandas.io.msgpack',
              'venv.lib.python3.7.site-packages.pandas.io.clipboard', 'venv.lib.python3.7.site-packages.pandas.api',
              'venv.lib.python3.7.site-packages.pandas.api.types',
              'venv.lib.python3.7.site-packages.pandas.api.extensions', 'venv.lib.python3.7.site-packages.pandas.core',
              'venv.lib.python3.7.site-packages.pandas.core.util', 'venv.lib.python3.7.site-packages.pandas.core.tools',
              'venv.lib.python3.7.site-packages.pandas.core.arrays',
              'venv.lib.python3.7.site-packages.pandas.core.dtypes',
              'venv.lib.python3.7.site-packages.pandas.core.sparse',
              'venv.lib.python3.7.site-packages.pandas.core.groupby',
              'venv.lib.python3.7.site-packages.pandas.core.indexes',
              'venv.lib.python3.7.site-packages.pandas.core.reshape',
              'venv.lib.python3.7.site-packages.pandas.core.computation',
              'venv.lib.python3.7.site-packages.pandas.util', 'venv.lib.python3.7.site-packages.pandas._libs',
              'venv.lib.python3.7.site-packages.pandas._libs.tslibs', 'venv.lib.python3.7.site-packages.pandas.tests',
              'venv.lib.python3.7.site-packages.pandas.tests.io',
              'venv.lib.python3.7.site-packages.pandas.tests.io.sas',
              'venv.lib.python3.7.site-packages.pandas.tests.io.json',
              'venv.lib.python3.7.site-packages.pandas.tests.io.parser',
              'venv.lib.python3.7.site-packages.pandas.tests.io.formats',
              'venv.lib.python3.7.site-packages.pandas.tests.io.msgpack',
              'venv.lib.python3.7.site-packages.pandas.tests.api', 'venv.lib.python3.7.site-packages.pandas.tests.util',
              'venv.lib.python3.7.site-packages.pandas.tests.frame',
              'venv.lib.python3.7.site-packages.pandas.tests.tools',
              'venv.lib.python3.7.site-packages.pandas.tests.dtypes',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.period',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.timedelta',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.timestamp',
              'venv.lib.python3.7.site-packages.pandas.tests.series',
              'venv.lib.python3.7.site-packages.pandas.tests.series.indexing',
              'venv.lib.python3.7.site-packages.pandas.tests.sparse',
              'venv.lib.python3.7.site-packages.pandas.tests.sparse.frame',
              'venv.lib.python3.7.site-packages.pandas.tests.sparse.series',
              'venv.lib.python3.7.site-packages.pandas.tests.tslibs',
              'venv.lib.python3.7.site-packages.pandas.tests.generic',
              'venv.lib.python3.7.site-packages.pandas.tests.groupby',
              'venv.lib.python3.7.site-packages.pandas.tests.groupby.aggregate',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.period',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib.python3.7.site-packages.pandas.tests.reshape',
              'venv.lib.python3.7.site-packages.pandas.tests.reshape.merge',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries.offsets',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.plotting',
              'venv.lib.python3.7.site-packages.pandas.tests.extension',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.base',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.json',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.decimal',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.category',
              'venv.lib.python3.7.site-packages.pandas.tests.internals',
              'venv.lib.python3.7.site-packages.pandas.tests.categorical',
              'venv.lib.python3.7.site-packages.pandas.tests.computation',
              'venv.lib.python3.7.site-packages.pandas.tools', 'venv.lib.python3.7.site-packages.pandas.types',
              'venv.lib.python3.7.site-packages.pandas.compat', 'venv.lib.python3.7.site-packages.pandas.compat.numpy',
              'venv.lib.python3.7.site-packages.pandas.errors', 'venv.lib.python3.7.site-packages.pandas.formats',
              'venv.lib.python3.7.site-packages.pandas.tseries', 'venv.lib.python3.7.site-packages.pandas.plotting',
              'venv.lib.python3.7.site-packages.pandas.computation', 'venv.lib.python3.7.site-packages.alembic',
              'venv.lib.python3.7.site-packages.alembic.ddl', 'venv.lib.python3.7.site-packages.alembic.util',
              'venv.lib.python3.7.site-packages.alembic.script', 'venv.lib.python3.7.site-packages.alembic.runtime',
              'venv.lib.python3.7.site-packages.alembic.testing',
              'venv.lib.python3.7.site-packages.alembic.testing.plugin',
              'venv.lib.python3.7.site-packages.alembic.operations',
              'venv.lib.python3.7.site-packages.alembic.autogenerate', 'venv.lib.python3.7.site-packages.certifi',
              'venv.lib.python3.7.site-packages.chardet', 'venv.lib.python3.7.site-packages.chardet.cli',
              'venv.lib.python3.7.site-packages.urllib3', 'venv.lib.python3.7.site-packages.urllib3.util',
              'venv.lib.python3.7.site-packages.urllib3.contrib',
              'venv.lib.python3.7.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.urllib3.packages',
              'venv.lib.python3.7.site-packages.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.botocore', 'venv.lib.python3.7.site-packages.botocore.docs',
              'venv.lib.python3.7.site-packages.botocore.docs.bcdoc',
              'venv.lib.python3.7.site-packages.botocore.vendored',
              'venv.lib.python3.7.site-packages.botocore.vendored.requests',
              'venv.lib.python3.7.site-packages.botocore.vendored.requests.packages',
              'venv.lib.python3.7.site-packages.botocore.vendored.requests.packages.chardet',
              'venv.lib.python3.7.site-packages.botocore.vendored.requests.packages.urllib3',
              'venv.lib.python3.7.site-packages.botocore.vendored.requests.packages.urllib3.util',
              'venv.lib.python3.7.site-packages.botocore.vendored.requests.packages.urllib3.contrib',
              'venv.lib.python3.7.site-packages.botocore.vendored.requests.packages.urllib3.packages',
              'venv.lib.python3.7.site-packages.botocore.vendored.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.dateutil', 'venv.lib.python3.7.site-packages.dateutil.tz',
              'venv.lib.python3.7.site-packages.dateutil.parser', 'venv.lib.python3.7.site-packages.dateutil.zoneinfo',
              'venv.lib.python3.7.site-packages.docutils', 'venv.lib.python3.7.site-packages.docutils.utils',
              'venv.lib.python3.7.site-packages.docutils.utils.math',
              'venv.lib.python3.7.site-packages.docutils.parsers',
              'venv.lib.python3.7.site-packages.docutils.parsers.rst',
              'venv.lib.python3.7.site-packages.docutils.parsers.rst.languages',
              'venv.lib.python3.7.site-packages.docutils.parsers.rst.directives',
              'venv.lib.python3.7.site-packages.docutils.readers', 'venv.lib.python3.7.site-packages.docutils.writers',
              'venv.lib.python3.7.site-packages.docutils.writers.xetex',
              'venv.lib.python3.7.site-packages.docutils.writers.latex2e',
              'venv.lib.python3.7.site-packages.docutils.writers.odf_odt',
              'venv.lib.python3.7.site-packages.docutils.writers.s5_html',
              'venv.lib.python3.7.site-packages.docutils.writers.pep_html',
              'venv.lib.python3.7.site-packages.docutils.writers.html4css1',
              'venv.lib.python3.7.site-packages.docutils.writers.html5_polyglot',
              'venv.lib.python3.7.site-packages.docutils.languages',
              'venv.lib.python3.7.site-packages.docutils.transforms', 'venv.lib.python3.7.site-packages.jmespath',
              'venv.lib.python3.7.site-packages.psycopg2', 'venv.lib.python3.7.site-packages.psycopg2.tests',
              'venv.lib.python3.7.site-packages.requests', 'venv.lib.python3.7.site-packages.markupsafe',
              'venv.lib.python3.7.site-packages.s3transfer', 'venv.lib.python3.7.site-packages.setuptools',
              'venv.lib.python3.7.site-packages.setuptools.extern',
              'venv.lib.python3.7.site-packages.setuptools._vendor',
              'venv.lib.python3.7.site-packages.setuptools._vendor.packaging',
              'venv.lib.python3.7.site-packages.setuptools.command', 'venv.lib.python3.7.site-packages.sqlalchemy',
              'venv.lib.python3.7.site-packages.sqlalchemy.ext',
              'venv.lib.python3.7.site-packages.sqlalchemy.ext.declarative',
              'venv.lib.python3.7.site-packages.sqlalchemy.orm', 'venv.lib.python3.7.site-packages.sqlalchemy.sql',
              'venv.lib.python3.7.site-packages.sqlalchemy.util', 'venv.lib.python3.7.site-packages.sqlalchemy.event',
              'venv.lib.python3.7.site-packages.sqlalchemy.engine',
              'venv.lib.python3.7.site-packages.sqlalchemy.testing',
              'venv.lib.python3.7.site-packages.sqlalchemy.testing.suite',
              'venv.lib.python3.7.site-packages.sqlalchemy.testing.plugin',
              'venv.lib.python3.7.site-packages.sqlalchemy.dialects',
              'venv.lib.python3.7.site-packages.sqlalchemy.dialects.mssql',
              'venv.lib.python3.7.site-packages.sqlalchemy.dialects.mysql',
              'venv.lib.python3.7.site-packages.sqlalchemy.dialects.oracle',
              'venv.lib.python3.7.site-packages.sqlalchemy.dialects.sqlite',
              'venv.lib.python3.7.site-packages.sqlalchemy.dialects.sybase',
              'venv.lib.python3.7.site-packages.sqlalchemy.dialects.firebird',
              'venv.lib.python3.7.site-packages.sqlalchemy.dialects.postgresql',
              'venv.lib.python3.7.site-packages.sqlalchemy.databases',
              'venv.lib.python3.7.site-packages.sqlalchemy.connectors',
              'venv.lib.python3.7.site-packages.pkg_resources', 'venv.lib.python3.7.site-packages.pkg_resources.extern',
              'venv.lib.python3.7.site-packages.pkg_resources._vendor',
              'venv.lib.python3.7.site-packages.pkg_resources._vendor.packaging', 'housing', 'housing.models',
              'housing.Scrapper'],
    url='',
    license='',
    author='bouamama amine',
    author_email='',
    description=''
)
