"""initial

Revision ID: b89bcb3c0fd0
Revises: 
Create Date: 2018-12-09 22:58:49.496788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eaa4382afdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('web_site', sa.Enum('PAP', 'SeLoger', name='websites'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('hash_doc', sa.String(length=256), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
